Install the libraries

In [1]:
import pandas as pd
import numpy as np
import random

from faker import Faker

fake = Faker()
np.random.seed(42)
random.seed(42)

If Faker isn't installed:

In [2]:
pip install faker pandas numpy

Requirement already satisfied: faker in c:\users\fadi\anaconda3\lib\site-packages (40.38.0)
Requirement already satisfied: pandas in c:\users\fadi\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\fadi\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: tzdata in c:\users\fadi\anaconda3\lib\site-packages (from faker) (2025.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\fadi\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\fadi\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\fadi\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

Generate regions

In [3]:
regions = pd.DataFrame({
    "Region_ID": ["R01", "R02", "R03", "R04", "R05"],
    "Region": [
        "North",
        "South",
        "East",
        "West",
        "Central"
    ]
})

regions

  Region_ID   Region
0       R01    North
1       R02    South
2       R03     East
3       R04     West
4       R05  Central

Generate customers

In [4]:
n_customers = 5000

segments = [
    "Consumer",
    "Corporate",
    "Small Business"
]

customers = pd.DataFrame({
    "Customer_ID": [
        f"CUST{i:05d}"
        for i in range(1, n_customers + 1)
    ],

    "Customer_Name": [
        fake.name()
        for _ in range(n_customers)
    ],

    "Segment": np.random.choice(
        segments,
        size=n_customers,
        p=[0.60, 0.20, 0.20]
    ),

    "Region_ID": np.random.choice(
        regions["Region_ID"],
        size=n_customers,
        p=[0.20, 0.18, 0.22, 0.25, 0.15]
    ),

    "Customer_Since": pd.to_datetime(
        np.random.choice(
            pd.date_range(
                "2019-01-01",
                "2024-12-31"
            ),
            size=n_customers
        )
    )
})

customers.head()

  Customer_ID   Customer_Name         Segment Region_ID Customer_Since
0   CUST00001  Megan Gonzalez        Consumer       R03     2021-05-13
1   CUST00002  Benjamin Young  Small Business       R03     2021-11-03
2   CUST00003     Jacob Adams       Corporate       R05     2020-08-17
3   CUST00004      Kevin Wolf        Consumer       R02     2022-03-28
4   CUST00005     Linda Lopez        Consumer       R05     2023-02-26

Generate products

In [5]:
categories = {
    "Technology": [
        "Laptops",
        "Monitors",
        "Accessories",
        "Phones"
    ],

    "Furniture": [
        "Chairs",
        "Desks",
        "Storage",
        "Tables"
    ],

    "Office Supplies": [
        "Paper",
        "Writing",
        "Binders",
        "Stationery"
    ],

    "Home": [
        "Kitchen",
        "Decor",
        "Lighting",
        "Appliances"
    ]
}

In [6]:
n_products = 200

product_rows = []

for i in range(1, n_products + 1):

    category = random.choice(
        list(categories.keys())
    )

    sub_category = random.choice(
        categories[category]
    )

    unit_cost = round(
        np.random.uniform(5, 800),
        2
    )

    markup = np.random.uniform(
        1.15,
        2.2
    )

    list_price = round(
        unit_cost * markup,
        2
    )

    product_rows.append({
        "Product_ID": f"PROD{i:04d}",
        "Product_Name": f"{sub_category} Product {i:03d}",
        "Category": category,
        "Sub_Category": sub_category,
        "Unit_Cost": unit_cost,
        "List_Price": list_price
    })

products = pd.DataFrame(product_rows)

products.head()

,Product_ID,Product_Name,Category,Sub_Category,Unit_Cost,List_Price
0,PROD0001,Laptops Product 001,Technology,Laptops,200.76,412.94
1,PROD0002,Writing Product 002,Office Supplies,Writing,254.49,358.17
2,PROD0003,Desks Product 003,Furniture,Desks,602.71,704.25
3,PROD0004,Laptops Product 004,Technology,Laptops,218.07,336.74
4,PROD0005,Kitchen Product 005,Home,Kitchen,706.38,1517.28

Generate orders

In [7]:
n_orders = 30000

orders = pd.DataFrame({
    "Order_ID": [
        f"ORD{i:06d}"
        for i in range(1, n_orders + 1)
    ],

    "Order_Date": pd.to_datetime(
        np.random.choice(
            pd.date_range(
                "2022-01-01",
                "2025-12-31"
            ),
            size=n_orders
        )
    ),

    "Customer_ID": np.random.choice(
        customers["Customer_ID"],
        size=n_orders
    ),

    "Sales_Channel": np.random.choice(
        ["Online", "Retail"],
        size=n_orders,
        p=[0.65, 0.35]
    ),

    "Payment_Method": np.random.choice(
        [
            "Credit Card",
            "Debit Card",
            "Bank Transfer",
            "PayPal"
        ],
        size=n_orders,
        p=[0.45, 0.25, 0.15, 0.15]
    )
})

In [8]:
orders = orders.merge(
    customers[
        ["Customer_ID", "Region_ID"]
    ],
    on="Customer_ID",
    how="left"
)

orders.head()

    Order_ID Order_Date Customer_ID Sales_Channel Payment_Method Region_ID
0  ORD000001 2025-01-30   CUST01818        Online    Credit Card       R05
1  ORD000002 2022-09-21   CUST03927        Retail     Debit Card       R03
2  ORD000003 2024-08-02   CUST04019        Retail  Bank Transfer       R01
3  ORD000004 2024-07-08   CUST04295        Online     Debit Card       R05
4  ORD000005 2022-06-10   CUST00715        Online    Credit Card       R04

Generate order items

In [9]:
n_items = 60000

order_items = pd.DataFrame({
    "Order_Item_ID": [
        f"ITEM{i:07d}"
        for i in range(1, n_items + 1)
    ],

    "Order_ID": np.random.choice(
        orders["Order_ID"],
        size=n_items
    ),

    "Product_ID": np.random.choice(
        products["Product_ID"],
        size=n_items
    ),

    "Quantity": np.random.choice(
        [1, 2, 3, 4, 5, 6, 7, 8],
        size=n_items,
        p=[
            0.35,
            0.25,
            0.15,
            0.10,
            0.06,
            0.04,
            0.03,
            0.02
        ]
    ),

    "Discount": np.random.choice(
        [0, 0.05, 0.10, 0.15, 0.20, 0.30],
        size=n_items,
        p=[
            0.25,
            0.20,
            0.25,
            0.15,
            0.10,
            0.05
        ]
    )
})

order_items.head()

  Order_Item_ID   Order_ID Product_ID  Quantity  Discount
0   ITEM0000001  ORD009042   PROD0102         2      0.05
1   ITEM0000002  ORD020217   PROD0064         2      0.15
2   ITEM0000003  ORD012919   PROD0004         3      0.30
3   ITEM0000004  ORD015724   PROD0168         2      0.10
4   ITEM0000005  ORD029803   PROD0070         1      0.15

Create the analytical sales table

In [10]:
sales = (
    order_items
    .merge(
        orders,
        on="Order_ID",
        how="left"
    )
    .merge(
        products,
        on="Product_ID",
        how="left"
    )
    .merge(
        regions,
        on="Region_ID",
        how="left"
    )
)

In [11]:
sales["Revenue"] = (
    sales["Quantity"]
    * sales["List_Price"]
    * (1 - sales["Discount"])
)

sales["Cost"] = (
    sales["Quantity"]
    * sales["Unit_Cost"]
)

sales["Profit"] = (
    sales["Revenue"]
    - sales["Cost"]
)

sales["Profit_Margin"] = (
    sales["Profit"]
    / sales["Revenue"]
)

In [12]:
sales[
    [
        "Order_ID",
        "Product_Name",
        "Quantity",
        "Discount",
        "Revenue",
        "Cost",
        "Profit",
        "Profit_Margin"
    ]
].head()

,Order_ID,Product_Name,Quantity,Discount,Revenue,Cost,Profit,Profit_Margin
0,ORD009042,Monitors Product 102,2,0.05,1956.829,1182.02,774.809,0.395951
1,ORD020217,Binders Product 064,2,0.15,105.553,71.10,34.453,0.326405
2,ORD012919,Laptops Product 004,3,0.30,707.154,654.21,52.944,0.074869
3,ORD015724,Tables Product 168,2,0.10,765.054,408.14,356.914,0.466521
4,ORD029803,Storage Product 070,1,0.15,1009.035,545.31,463.725,0.459573

Now deliberately introduce data-quality problems

In [13]:
duplicate_rows = sales.sample(
    100,
    random_state=42
)

sales_raw = pd.concat(
    [sales, duplicate_rows],
    ignore_index=True
)

In [14]:
missing_customer_idx = sales_raw.sample(
    75,
    random_state=10
).index

sales_raw.loc[
    missing_customer_idx,
    "Customer_ID"
] = np.nan

In [15]:
missing_discount_idx = sales_raw.sample(
    50,
    random_state=20
).index

sales_raw.loc[
    missing_discount_idx,
    "Discount"
] = np.nan

In [16]:
technology_idx = sales_raw[
    "Category"
] == "Technology"

sample_idx = sales_raw[
    technology_idx
].sample(
    40,
    random_state=30
).index

sales_raw.loc[
    sample_idx,
    "Category"
] = "technology"

Save the raw dataset

In [17]:
sales_raw.to_csv(
    "../data/raw/sales_data.csv",
    index=False
)