In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [3]:
df = pd.read_csv("../data/raw/sales_data.csv")

df.head()

,Order_Item_ID,Order_ID,Product_ID,Quantity,Discount,Order_Date,Customer_ID,Sales_Channel,Payment_Method,Region_ID,Product_Name,Category,Sub_Category,Unit_Cost,List_Price,Region,Revenue,Cost,Profit,Profit_Margin
0,ITEM0000001,ORD009042,PROD0102,2,0.05,2022-05-21,CUST04933,Online,PayPal,R02,Monitors Product 102,Technology,Monitors,591.01,1029.91,South,1956.829,1182.02,774.809,0.395951
1,ITEM0000002,ORD020217,PROD0064,2,0.15,2025-05-04,CUST02364,Retail,Credit Card,R04,Binders Product 064,Office Supplies,Binders,35.55,62.09,West,105.553,71.10,34.453,0.326405
2,ITEM0000003,ORD012919,PROD0004,3,0.30,2023-10-05,CUST00853,Retail,Credit Card,R05,Laptops Product 004,Technology,Laptops,218.07,336.74,Central,707.154,654.21,52.944,0.074869
3,ITEM0000004,ORD015724,PROD0168,2,0.10,2023-04-16,CUST01937,Online,Credit Card,R02,Tables Product 168,Furniture,Tables,204.07,425.03,South,765.054,408.14,356.914,0.466521
4,ITEM0000005,ORD029803,PROD0070,1,0.15,2022-08-26,CUST00959,Online,Credit Card,R04,Storage Product 070,Furniture,Storage,545.31,1187.10,West,1009.035,545.31,463.725,0.459573

In [4]:
df.shape

(60100, 20)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60100 entries, 0 to 60099
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_Item_ID   60100 non-null  object
 1   Order_ID        60100 non-null  object
 2   Product_ID      60100 non-null  object
 3   Quantity        60100 non-null  int64
 4   Discount        60050 non-null  float64
 5   Order_Date      60100 non-null  object
 6   Customer_ID     60025 non-null  object
 7   Sales_Channel   60100 non-null  object
 8   Payment_Method  60100 non-null  object
 9   Region_ID       60100 non-null  object
 10  Product_Name    60100 non-null  object
 11  Category        60100 non-null  object
 12  Sub_Category    60100 non-null  object
 13  Unit_Cost       60100 non-null  float64
 14  List_Price      60100 non-null  float64
 15  Region          60100 non-null  object
 16  Revenue         60100 non-null  float64
 17  Cost            60100 non-null  float64
 18  Profit          60100 non-null  float64
 19  Profit_Margin   60100 non-null  float64
dtypes: float64(7), int64(1), object(12)
memory usage: 9.2+ MB

In [6]:
df.describe(include="all")

,Order_Item_ID,Order_ID,Product_ID,Quantity,Discount,Order_Date,Customer_ID,Sales_Channel,Payment_Method,Region_ID,Product_Name,Category,Sub_Category,Unit_Cost,List_Price,Region,Revenue,Cost,Profit,Profit_Margin
count,60100,60100,60100,60100.000000,60050.000000,60100,60025,60100,60100,60100,60100,60100,60100,60100.000000,60100.000000,60100,60100.00000,60100.000000,60100.000000,60100.000000
unique,60000,25966,200,NaN,NaN,1461,4979,2,4,5,200,5,16,NaN,NaN,5,NaN,NaN,NaN,NaN
top,ITEM0042188,ORD007049,PROD0153,NaN,NaN,2023-06-27,CUST04295,Online,Credit Card,R04,Tables Product 153,Home,Monitors,NaN,NaN,West,NaN,NaN,NaN,NaN
freq,2,10,347,NaN,NaN,85,41,38780,27117,14187,347,16105,6111,NaN,NaN,14187,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,2.613428,0.092406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,412.183240,704.776211,NaN,1672.82401,1077.577073,595.246937,0.326313
std,NaN,NaN,NaN,1.782887,0.079547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,220.315465,404.509895,NaN,1647.77524,1017.245044,717.154497,0.139478
min,NaN,NaN,NaN,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.360000,27.640000,NaN,19.34800,16.360000,-658.410000,-0.222597
25%,NaN,NaN,NaN,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,226.670000,358.170000,NaN,590.46100,401.440000,139.950000,0.235809
50%,NaN,NaN,NaN,2.000000,0.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,415.630000,692.280000,NaN,1109.15350,725.110000,347.503000,0.348590
75%,NaN,NaN,NaN,4.000000,0.150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,581.240000,1042.140000,NaN,2194.07250,1450.220000,761.400000,0.436097
max,NaN,NaN,NaN,8.000000,0.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,796.880000,1664.580000,NaN,12583.28000,6375.040000,6546.080000,0.544842

In [7]:
df.nunique()

Order_Item_ID     60000
Order_ID          25966
Product_ID          200
Quantity              8
Discount              6
Order_Date         1461
Customer_ID        4979
Sales_Channel         2
Payment_Method        4
Region_ID             5
Product_Name        200
Category              5
Sub_Category         16
Unit_Cost           200
List_Price          200
Region                5
Revenue            8129
Cost               1600
Profit             8298
Profit_Margin      2401
dtype: int64

In [8]:
missing_values = df.isnull().sum()

missing_values[missing_values > 0]

Discount       50
Customer_ID    75
dtype: int64

In [9]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 100

In [10]:
print(df["Category"].value_counts(dropna=False))

Category
Home               16105
Technology         15519
Furniture          14387
Office Supplies    14049
technology            40
Name: count, dtype: int64

In [11]:
numeric_columns = [
    "Quantity",
    "Discount",
    "Unit_Cost",
    "List_Price",
    "Revenue",
    "Cost",
    "Profit",
    "Profit_Margin"
]

df[numeric_columns].describe()

,Quantity,Discount,Unit_Cost,List_Price,Revenue,Cost,Profit,Profit_Margin
count,60100.000000,60050.000000,60100.000000,60100.000000,60100.00000,60100.000000,60100.000000,60100.000000
mean,2.613428,0.092406,412.183240,704.776211,1672.82401,1077.577073,595.246937,0.326313
std,1.782887,0.079547,220.315465,404.509895,1647.77524,1017.245044,717.154497,0.139478
min,1.000000,0.000000,16.360000,27.640000,19.34800,16.360000,-658.410000,-0.222597
25%,1.000000,0.000000,226.670000,358.170000,590.46100,401.440000,139.950000,0.235809
50%,2.000000,0.100000,415.630000,692.280000,1109.15350,725.110000,347.503000,0.348590
75%,4.000000,0.150000,581.240000,1042.140000,2194.07250,1450.220000,761.400000,0.436097
max,8.000000,0.300000,796.880000,1664.580000,12583.28000,6375.040000,6546.080000,0.544842

In [13]:
print("Negative quantities:", (df["Quantity"] < 0).sum())
print("Negative prices:", (df["List_Price"] < 0).sum())
print("Negative discounts:", (df["Discount"] < 0).sum())
print("Discounts above 100%:", (df["Discount"] > 1).sum())

Negative quantities: 0
Negative prices: 0
Negative discounts: 0
Discounts above 100%: 0

In [14]:
df["Order_Date"] = pd.to_datetime(
    df["Order_Date"],
    errors="coerce"
)

print("Invalid dates:", df["Order_Date"].isna().sum())

print("Minimum date:", df["Order_Date"].min())
print("Maximum date:", df["Order_Date"].max())

Invalid dates: 0
Minimum date: 2022-01-01 00:00:00
Maximum date: 2025-12-31 00:00:00

In [20]:
df.isnull().sum().sort_values(ascending=False)

Customer_ID       75
Discount          50
Order_Item_ID      0
Category           0
Profit             0
Cost               0
Revenue            0
Region             0
List_Price         0
Unit_Cost          0
Sub_Category       0
Product_Name       0
Order_ID           0
Region_ID          0
Payment_Method     0
Sales_Channel      0
Order_Date         0
Quantity           0
Product_ID         0
Profit_Margin      0
dtype: int64

In [21]:
df["Category"].value_counts(dropna=False)

Category
Home               16105
Technology         15519
Furniture          14387
Office Supplies    14049
technology            40
Name: count, dtype: int64

In [22]:
df[df.duplicated(keep=False)].sort_values("Order_ID").head(20)

,Order_Item_ID,Order_ID,Product_ID,Quantity,Discount,Order_Date,Customer_ID,Sales_Channel,Payment_Method,Region_ID,Product_Name,Category,Sub_Category,Unit_Cost,List_Price,Region,Revenue,Cost,Profit,Profit_Margin
60024,ITEM0031573,ORD000170,PROD0113,1,0.15,2025-07-29,CUST03862,Online,Credit Card,R04,Laptops Product 113,Technology,Laptops,174.29,271.91,West,231.1235,174.29,56.8335,0.245901
31572,ITEM0031573,ORD000170,PROD0113,1,0.15,2025-07-29,CUST03862,Online,Credit Card,R04,Laptops Product 113,Technology,Laptops,174.29,271.91,West,231.1235,174.29,56.8335,0.245901
53390,ITEM0053391,ORD000280,PROD0034,1,0.10,2023-01-10,CUST00753,Online,Credit Card,R01,Storage Product 034,Furniture,Storage,469.56,722.22,North,649.9980,469.56,180.4380,0.277598
60010,ITEM0053391,ORD000280,PROD0034,1,0.10,2023-01-10,CUST00753,Online,Credit Card,R01,Storage Product 034,Furniture,Storage,469.56,722.22,North,649.9980,469.56,180.4380,0.277598
29209,ITEM0029210,ORD000312,PROD0189,6,0.00,2023-08-28,CUST04453,Online,Debit Card,R01,Stationery Product 189,Office Supplies,Stationery,792.55,1132.23,North,6793.3800,4755.30,2038.0800,0.300010
60058,ITEM0029210,ORD000312,PROD0189,6,0.00,2023-08-28,CUST04453,Online,Debit Card,R01,Stationery Product 189,Office Supplies,Stationery,792.55,1132.23,North,6793.3800,4755.30,2038.0800,0.300010
60085,ITEM0003223,ORD000431,PROD0010,1,0.05,2025-04-06,CUST04231,Online,Credit Card,R03,Lighting Product 010,Home,Lighting,719.78,1374.27,East,1305.5565,719.78,585.7765,0.448680
3222,ITEM0003223,ORD000431,PROD0010,1,0.05,2025-04-06,CUST04231,Online,Credit Card,R03,Lighting Product 010,Home,Lighting,719.78,1374.27,East,1305.5565,719.78,585.7765,0.448680
60044,ITEM0032219,ORD000444,PROD0045,2,0.00,2025-08-14,CUST00195,Online,Debit Card,R02,Writing Product 045,Office Supplies,Writing,489.74,704.28,South,1408.5600,979.48,429.0800,0.304623
32218,ITEM0032219,ORD000444,PROD0045,2,0.00,2025-08-14,CUST00195,Online,Debit Card,R02,Writing Product 045,Office Supplies,Writing,489.74,704.28,South,1408.5600,979.48,429.0800,0.304623
23428,ITEM0023429,ORD000522,PROD0097,2,0.15,2024-06-25,CUST04689,Retail,Credit Card,R03,Decor Product 097,Home,Decor,712.95,1042.14,East,1771.6380,1425.90,345.7380,0.195152
60013,ITEM0023429,ORD000522,PROD0097,2,0.15,2024-06-25,CUST04689,Retail,Credit Card,R03,Decor Product 097,Home,Decor,712.95,1042.14,East,1771.6380,1425.90,345.7380,0.195152
60036,ITEM0044172,ORD000587,PROD0084,1,0.15,2024-06-04,CUST00756,Online,PayPal,R03,Decor Product 084,Home,Decor,495.44,975.20,East,828.9200,495.44,333.4800,0.402307
44171,ITEM0044172,ORD000587,PROD0084,1,0.15,2024-06-04,CUST00756,Online,PayPal,R03,Decor Product 084,Home,Decor,495.44,975.20,East,828.9200,495.44,333.4800,0.402307
1334,ITEM0001335,ORD001154,PROD0192,7,0.05,2025-05-09,CUST04865,Online,Bank Transfer,R04,Tables Product 192,Furniture,Tables,509.90,1070.93,West,7121.6845,3569.30,3552.3845,0.498812
60092,ITEM0001335,ORD001154,PROD0192,7,0.05,2025-05-09,CUST04865,Online,Bank Transfer,R04,Tables Product 192,Furniture,Tables,509.90,1070.93,West,7121.6845,3569.30,3552.3845,0.498812
37978,ITEM0037979,ORD001383,PROD0119,1,0.00,2025-02-02,CUST02916,Online,Credit Card,R02,Tables Product 119,Furniture,Tables,204.02,259.11,South,259.1100,204.02,55.0900,0.212612
60035,ITEM0037979,ORD001383,PROD0119,1,0.00,2025-02-02,CUST02916,Online,Credit Card,R02,Tables Product 119,Furniture,Tables,204.02,259.11,South,259.1100,204.02,55.0900,0.212612
60080,ITEM0001867,ORD001450,PROD0197,2,0.05,2025-12-28,CUST00113,Retail,Bank Transfer,R04,Lighting Product 197,Home,Lighting,518.44,722.08,West,1371.9520,1036.88,335.0720,0.244230
1866,ITEM0001867,ORD001450,PROD0197,2,0.05,2025-12-28,CUST00113,Retail,Bank Transfer,R04,Lighting Product 197,Home,Lighting,518.44,722.08,West,1371.9520,1036.88,335.0720,0.244230

In [24]:
duplicate_rows = df[df.duplicated(keep=False)]

duplicate_rows.shape

(200, 20)

In [25]:
duplicate_rows.duplicated().sum()

np.int64(100)

In [26]:
df[df["Category"].str.lower() == "technology"]["Category"].value_counts()

Category
Technology    15519
technology       40
Name: count, dtype: int64

In [27]:
df["Category"] = df["Category"].str.strip().str.title()

In [28]:
df["Category"].value_counts()

Category
Home               16105
Technology         15559
Furniture          14387
Office Supplies    14049
Name: count, dtype: int64

In [29]:
df["Category"] = df["Category"].str.strip().str.title()

df["Category"].value_counts()

Category
Home               16105
Technology         15559
Furniture          14387
Office Supplies    14049
Name: count, dtype: int64

In [30]:
df.isnull().sum().sort_values(ascending=False)

Customer_ID       75
Discount          50
Order_Item_ID      0
Category           0
Profit             0
Cost               0
Revenue            0
Region             0
List_Price         0
Unit_Cost          0
Sub_Category       0
Product_Name       0
Order_ID           0
Region_ID          0
Payment_Method     0
Sales_Channel      0
Order_Date         0
Quantity           0
Product_ID         0
Profit_Margin      0
dtype: int64

In [31]:
missing = df.isnull().sum()

missing[missing > 0]

Discount       50
Customer_ID    75
dtype: int64

Handle missing Discount

In [33]:
df["Discount"] = df["Discount"].fillna(0)

In [34]:
df["Discount"].isnull().sum()

np.int64(0)

Handle missing Customer_ID

In [35]:
df["Customer_ID"].isnull().sum()

np.int64(75)

Recalculate the financial metrics

In [36]:
df["Revenue"] = (
    df["Quantity"]
    * df["List_Price"]
    * (1 - df["Discount"])
)

df["Cost"] = (
    df["Quantity"]
    * df["Unit_Cost"]
)

df["Profit"] = (
    df["Revenue"]
    - df["Cost"]
)

df["Profit_Margin"] = (
    df["Profit"]
    / df["Revenue"]
)

Now deal with the 100 duplicates

In [37]:
df.duplicated().sum()

np.int64(100)

In [38]:
duplicates = df[df.duplicated(keep=False)]

duplicates.sort_values(
    "Order_Item_ID"
).head(20)

,Order_Item_ID,Order_ID,Product_ID,Quantity,Discount,Order_Date,Customer_ID,Sales_Channel,Payment_Method,Region_ID,Product_Name,Category,Sub_Category,Unit_Cost,List_Price,Region,Revenue,Cost,Profit,Profit_Margin
273,ITEM0000274,ORD024412,PROD0085,1,0.00,2023-08-06,CUST02752,Online,Credit Card,R04,Tables Product 085,Furniture,Tables,455.58,633.84,West,633.8400,455.58,178.2600,0.281238
60051,ITEM0000274,ORD024412,PROD0085,1,0.00,2023-08-06,CUST02752,Online,Credit Card,R04,Tables Product 085,Furniture,Tables,455.58,633.84,West,633.8400,455.58,178.2600,0.281238
1334,ITEM0001335,ORD001154,PROD0192,7,0.05,2025-05-09,CUST04865,Online,Bank Transfer,R04,Tables Product 192,Furniture,Tables,509.90,1070.93,West,7121.6845,3569.30,3552.3845,0.498812
60092,ITEM0001335,ORD001154,PROD0192,7,0.05,2025-05-09,CUST04865,Online,Bank Transfer,R04,Tables Product 192,Furniture,Tables,509.90,1070.93,West,7121.6845,3569.30,3552.3845,0.498812
1866,ITEM0001867,ORD001450,PROD0197,2,0.05,2025-12-28,CUST00113,Retail,Bank Transfer,R04,Lighting Product 197,Home,Lighting,518.44,722.08,West,1371.9520,1036.88,335.0720,0.244230
60080,ITEM0001867,ORD001450,PROD0197,2,0.05,2025-12-28,CUST00113,Retail,Bank Transfer,R04,Lighting Product 197,Home,Lighting,518.44,722.08,West,1371.9520,1036.88,335.0720,0.244230
2218,ITEM0002219,ORD007205,PROD0059,2,0.00,2022-11-09,CUST01625,Online,Debit Card,R04,Writing Product 059,Office Supplies,Writing,395.89,818.00,West,1636.0000,791.78,844.2200,0.516027
60076,ITEM0002219,ORD007205,PROD0059,2,0.00,2022-11-09,CUST01625,Online,Debit Card,R04,Writing Product 059,Office Supplies,Writing,395.89,818.00,West,1636.0000,791.78,844.2200,0.516027
2885,ITEM0002886,ORD029470,PROD0057,4,0.00,2022-10-15,CUST00364,Online,Bank Transfer,R04,Accessories Product 057,Technology,Accessories,761.90,1549.87,West,6199.4800,3047.60,3151.8800,0.508410
60045,ITEM0002886,ORD029470,PROD0057,4,0.00,2022-10-15,CUST00364,Online,Bank Transfer,R04,Accessories Product 057,Technology,Accessories,761.90,1549.87,West,6199.4800,3047.60,3151.8800,0.508410
3222,ITEM0003223,ORD000431,PROD0010,1,0.05,2025-04-06,CUST04231,Online,Credit Card,R03,Lighting Product 010,Home,Lighting,719.78,1374.27,East,1305.5565,719.78,585.7765,0.448680
60085,ITEM0003223,ORD000431,PROD0010,1,0.05,2025-04-06,CUST04231,Online,Credit Card,R03,Lighting Product 010,Home,Lighting,719.78,1374.27,East,1305.5565,719.78,585.7765,0.448680
3502,ITEM0003503,ORD019963,PROD0039,4,0.10,2023-08-13,CUST01350,Online,Credit Card,R04,Writing Product 039,Office Supplies,Writing,626.77,1071.44,West,3857.1840,2507.08,1350.1040,0.350023
60074,ITEM0003503,ORD019963,PROD0039,4,0.10,2023-08-13,CUST01350,Online,Credit Card,R04,Writing Product 039,Office Supplies,Writing,626.77,1071.44,West,3857.1840,2507.08,1350.1040,0.350023
3803,ITEM0003804,ORD025063,PROD0129,3,0.30,2023-10-31,CUST01596,Retail,PayPal,R02,Kitchen Product 129,Home,Kitchen,63.87,105.76,South,222.0960,191.61,30.4860,0.137265
60027,ITEM0003804,ORD025063,PROD0129,3,0.30,2023-10-31,CUST01596,Retail,PayPal,R02,Kitchen Product 129,Home,Kitchen,63.87,105.76,South,222.0960,191.61,30.4860,0.137265
60084,ITEM0003868,ORD005356,PROD0128,1,0.00,2025-07-16,CUST04094,Online,Credit Card,R04,Laptops Product 128,Technology,Laptops,228.35,397.97,West,397.9700,228.35,169.6200,0.426213
3867,ITEM0003868,ORD005356,PROD0128,1,0.00,2025-07-16,CUST04094,Online,Credit Card,R04,Laptops Product 128,Technology,Laptops,228.35,397.97,West,397.9700,228.35,169.6200,0.426213
60012,ITEM0005027,ORD015520,PROD0146,2,0.10,2024-01-27,CUST04385,Retail,Debit Card,R03,Laptops Product 146,Technology,Laptops,19.56,27.64,East,49.7520,39.12,10.6320,0.213700
5026,ITEM0005027,ORD015520,PROD0146,2,0.10,2024-01-27,CUST04385,Retail,Debit Card,R03,Laptops Product 146,Technology,Laptops,19.56,27.64,East,49.7520,39.12,10.6320,0.213700

In [39]:
duplicates.duplicated().sum()

np.int64(100)

In [40]:
df = df.drop_duplicates().copy()

In [41]:
print("Rows after removing duplicates:", len(df))
print("Remaining duplicates:", df.duplicated().sum())

Rows after removing duplicates: 60000
Remaining duplicates: 0

Validate the cleaned dataset

Check dimensions

In [42]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 60000
Columns: 20

Check duplicates

In [43]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

Check missing values

In [45]:
df.isnull().sum()[df.isnull().sum() > 0]

Customer_ID    75
dtype: int64

Check categories

In [46]:
df["Category"].value_counts()

Category
Home               16076
Technology         15531
Furniture          14365
Office Supplies    14028
Name: count, dtype: int64

Validate quantities

In [47]:
print("Invalid quantities:", (df["Quantity"] <= 0).sum())

Invalid quantities: 0

Validate discounts

In [48]:
print("Invalid discounts:", ((df["Discount"] < 0) | (df["Discount"] > 1)).sum())

Invalid discounts: 0

Validate prices

In [49]:
print("Invalid unit costs:", (df["Unit_Cost"] < 0).sum())
print("Invalid list prices:", (df["List_Price"] < 0).sum())

Invalid unit costs: 0
Invalid list prices: 0

Validate financial calculations

In [50]:
revenue_check = (
    df["Quantity"]
    * df["List_Price"]
    * (1 - df["Discount"])
)

profit_check = revenue_check - (
    df["Quantity"] * df["Unit_Cost"]
)

print(
    "Revenue calculation errors:",
    (~np.isclose(df["Revenue"], revenue_check)).sum()
)

print(
    "Profit calculation errors:",
    (~np.isclose(df["Profit"], profit_check)).sum()
)

Revenue calculation errors: 0
Profit calculation errors: 0

Check dates

In [51]:
print("Earliest order:", df["Order_Date"].min())
print("Latest order:", df["Order_Date"].max())
print("Invalid dates:", df["Order_Date"].isna().sum())

Earliest order: 2022-01-01 00:00:00
Latest order: 2025-12-31 00:00:00
Invalid dates: 0

Save the cleaned dataset

In [53]:
df.to_csv(
    "../data/cleaned/sales_cleaned.csv",
    index=False
)